### ISSUE TITLE
Persist The data of GeoServer in Docker (configure GeoServer to have the map locally)

### ISSUE THREAD

**Issue by yasminehilout** [XavierGuertin/WildfireVisualizationProject#115]
**As a user,** I want GeoServer to persist its data in Docker so that the map configurations remain consistent and accessible locally across restarts or deployments.
- **Size/Points:** M (3)
- **Priority:** High
- **Risk:** Medium (GeoServer persistence can be complex due to file storage and configuration dependencies)
- **Child of Epic:** Infrastructure Setup
- **Ideal Time:** 3 days

**Acceptance Criteria:**
  - GeoServer must save its configuration and data locally within a Docker volume.
  - The persisted data should remain available after container restarts or re-deployments.
  - Documentation must detail the persistence setup and how to access or modify the stored data.

**Comment by PFratt** [comment]
This issue was completed in https://github.com/XavierGuertin/WildfireVisualizationProject/pull/110
