### ISSUE TITLE
Build user-friendly dataset selection panel

### ISSUE THREAD

**Issue by Adissuu** [XavierGuertin/WildfireVisualizationProject#27]
As a user, I want to easily select datasets from a user-friendly panel that dynamically filters based on my map region so that I can focus on relevant data..
- **Size/Points:** M (3)
- **Priority**: Medium
- **Risk:** Low
- **Child of Epic:** Frontend UI Development

Acceptance Criteria:
- The dataset panel must display available datasets based on the user’s current zoom region.
- When a dataset is selected, the sidebar should disappear, but a toolbar of options must remain accessible.
- Users must be able to toggle between viewing all datasets and filtering them by geographic region.

**Comment by im-samwong** [comment]
Duplicate story on #48
