### ISSUE TITLE
Set up SonarQube for code quality checks and automated testing

### ISSUE THREAD

**Issue by Adissuu** [XavierGuertin/WildfireVisualizationProject#33]
**As a user,** I want automated quality checks to ensure that the code being deployed meets quality and testing standards, so that I can avoid deploying broken code to production.
- **Size/Points:** M (3)
- **Priority:** Medium
- **Risk:** Medium (Needs integration with both backend and frontend code)
- **Child of Epic:** Infrastructure Setup

**Comment by XavierGuertin** [comment]
SonarQube has been connected and linked to the repo, configuration has been made so that one pushes, the analysis will be made.
