### ISSUE TITLE
Set up GitHub Actions for CI/CD pipelines for automated build and deployment

### ISSUE THREAD

**Issue by Adissuu** [XavierGuertin/WildfireVisualizationProject#34]
**As a user**, I want CI/CD pipelines to automatically build and deploy the application to reduce manual overhead and ensure that my code is continuously tested and deployed.
- **Size/Points**: M (3)
- **Priority:** High
- **Risk:** Medium (Integrating multiple services into CI/CD could have challenges)
- **Child of Epic:** Infrastructure Setup

Acceptance Criteria::
- A successful build should trigger automated tests and deployment via the CI/CD pipeline.
- Build status should be clearly visible in GitHub.
- Failed builds must provide detailed error messages for debugging.

**Comment by LiamDaigle** [comment]
CI for tests using Nx setup, aswell as the building of the images on docker. Just waiting on getting the docker hub setup so that we can upload our images after every merge.

**Comment by LiamDaigle** [comment]
CI is now setup to run tests to ensure that new code being pulled into dev doesn't break anything. It is also automatically being built and sent to docker hub.
