### ISSUE TITLE
Containerize GeoServer with Docker and ensure its integration with backend services

### ISSUE THREAD

**Issue by GetGabed** [XavierGuertin/WildfireVisualizationProject#36]
**As a user**, I want GeoServer to be containerized and connected to my backend so that geospatial data can be processed and served efficiently within a scalable architecture.

- **Size/Points:** L (5)
- **Priority**: High
- **Risk:** High (GeoServer has complex configuration and integration dependencies)
- **Child of Epic:** Infrastructure Setup
- **Ideal time:** 5 days
- **Acceptance Criteria:**
    - GeoServer should run in a Docker container and be fully accessible via backend APIs.
    - The backend must be able to connect to GeoServer for serving geospatial data.
    - The integration tests should confirm that the GeoServer endpoints are accessible from the backend.

**Comment by Fetyali7** [comment]
We managed to containerize it, but due to the bit of change in the requirements we pushed it back for release 1
