### ISSUE TITLE
Define and document API endpoints for data interaction between frontend and backend

### ISSUE THREAD

**Issue by im-samwong** [XavierGuertin/WildfireVisualizationProject#42]
As a user, I want clearly defined and documented API endpoints so that frontend and backend services can communicate efficiently.

Size/Points: M (3)
Priority: High
Risk: Low

**Comment by yasminehilout** [comment]
Here is the [initial draft of the API endpoints documentation](https://docs.google.com/document/d/1c8WZiLkVrweh59SD6Hu6NhUgC4PBzxoiuUpDT43_GTw/edit?usp=sharing). It is a comprehensive outline that we can refine and update as the project progresses. Looking forward to your feedback!

**Comment by yasminehilout** [comment]
We are currently awaiting sample datasets from the stakeholder, which are necessary to define and structure the API endpoints for data interaction between the frontend and backend. As a result, this task has been delayed and will be rescheduled for Iteration 4 (Release 1).

We will provide an update once the datasets are received and we can proceed with API development.

**Comment by XavierGuertin** [comment]
The wiki was created: [API Endpoints](https://github.com/XavierGuertin/WildfireVisualizationProject/wiki/API-endpoints)
