### ISSUE TITLE
Finalize the architecture design for microservices (communication, data flow)

### ISSUE THREAD

**Issue by im-samwong** [XavierGuertin/WildfireVisualizationProject#43]
As a user, I want a finalized architecture design to ensure proper communication and data flow between microservices for optimal performance.

Size/Points: L (5)
Priority: High
Risk: High

**Comment by yasminehilout** [comment]
Added the following Architecture Diagram to the [Wiki Page](https://github.com/XavierGuertin/WildfireVisualizationProject/wiki/Overall-Architecture-and-Class-Diagrams#architecture-overview):

![image](https://github.com/user-attachments/assets/b1eda45e-6b61-450f-a197-498df0f8f23b)

**Comment by yasminehilout** [comment]
Added the flowcharts done by @PFratt in the [Wiki Page](https://github.com/XavierGuertin/WildfireVisualizationProject/wiki/Overall-Architecture-and-Class-Diagrams#2-application-workflow-diagrams).
