### ISSUE TITLE
Create Mockups for the Wildfire Visualization Platform

### ISSUE THREAD

**Issue by im-samwong** [XavierGuertin/WildfireVisualizationProject#46]
As a user (UI/UX designer or stakeholder), I want to create mockups for the Wildfire Visualization Platform so that the development team and stakeholders can visualize the user interface before starting development and ensure it meets user needs.
- Size/Points: M (3)
- Priority: High
- Risk: Medium (delays or miscommunication in UI design could impact development timelines)
- Child of Epic: Frontend UI Development****

**Comment by yasminehilout** [comment]
The initial mockup for the Wildfire Visualization Platform has been added to the Wiki. You can view it here: [UI Mockups](https://github.com/XavierGuertin/WildfireVisualizationProject/wiki/UI-Mockups).

This page includes the main page mockup, outlining the interface layout, key elements, and functionality as described in the System Requirements Document.
