### ISSUE TITLE
Add dataset metadata display for selected datasets 

### ISSUE THREAD

**Issue by im-samwong** [XavierGuertin/WildfireVisualizationProject#47]
As a user, I want to view the metadata (name, description, data format, processes, source) of the selected dataset so that I can better understand its details before using it.
- Size/Points: M (3)
- Priority: High
- Risk: Medium (Requires dynamic UI updates and integration with metadata)
- Child of Epic: Frontend UI Development

Acceptance Criteria:
- When a dataset is selected, a window must display its metadata (name, description, data format, processes required, and source).
- Metadata should update dynamically as the user selects different datasets.

**Comment by LiamDaigle** [comment]
Initial design is completed, will close the ticket once I implement the collapsable window
