### ISSUE TITLE
 [Bug] Excessive Usage of NX Cloud with Local Commands

### ISSUE THREAD

**Issue by im-samwong** [XavierGuertin/WildfireVisualizationProject#74]
**Description:**
While running local commands in the NX workspace, NX Cloud was being overused despite configuration settings that should limit or prevent NX Cloud tasks. Expected behavior was for NX to run commands locally without triggering NX Cloud processes, but the build and test tasks consistently utilized NX Cloud, potentially leading to unnecessary cache sharing and network usage.

**Steps to Reproduce:**

1. Set up a standard NX workspace with a local configuration.
2. Run local commands such as `nx build frontend` or `nx test frontend`.
3. Observe whether NX Cloud is triggered in the task processing.
4. Verify settings in `nx.json` to ensure `tasksRunnerOptions` is disabled or set for local execution only.

**Expected Behavior:**
Local NX commands should execute locally, without relying on NX Cloud or triggering remote caching processes unless explicitly configured to do so.

**Actual Behavior:**
NX Cloud was used even though the configuration specified local execution, resulting in higher network usage and possible task queuing on NX Cloud. This behavior caused unexpected delays and overuse of NX Cloud resources.

**Screenshots / Visuals:**
_N/A for this issue as it's a backend processing issue, but logs indicating NX Cloud usage can be provided if necessary._

**Environment Details:**

- **OS**: Windows 10

**Additional Context / Notes:**
This issue may stem from `nx.json` configuration not being respected, or possible bugs in the handling of `tasksRunnerOptions`. Disabling NX Cloud manually per command (`NX_CLOUD=false nx <command>`) mitigates the problem, but this should ideally respect workspace settings. Further testing indicated the issue persists across various NX versions and environments.

---

Please let me know if further information or logs are needed to assist in troubleshooting this issue.

**Comment by LiamDaigle** [comment]
Finished!
