### ISSUE TITLE
Initialize Database and Dockerize PostgreSQL Instance

### ISSUE THREAD

**Issue by GetGabed** [XavierGuertin/WildfireVisualizationProject#79]
As a developer, I want to initialize the PostgreSQL database and create a Dockerized PostgreSQL instance so that the environment is easily reproducible and ready for data storage.

Size/Points: M (5)
Priority: High
Risk: Medium

Acceptance Criteria:

- A Dockerfile and ``docker-compose.yml`` are created to set up a PostgreSQL instance with appropriate configuration (e.g., port, volume for data persistence).
- PostgreSQL instance initializes successfully with required roles and permissions.
- Documentation is updated with setup instructions for running the database locally in a Docker container.
- Database is accessible and responsive for subsequent components (DataPuller, DataConverter).

**Comment by XavierGuertin** [comment]
this issue has been done part of #63
